apiVersion: v1
kind: Service
metadata:
  labels:
    service: uda-person
  name: uda-person
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 30002
  selector:
    service: uda-person
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: uda-person
  name: uda-person
spec:
  replicas: 1
  selector:
    matchLabels:
      service: uda-person
  template:
    metadata:
      labels:
        service: uda-person
    spec:
      containers:
      - image: samerzmd/uda-person:latest
        name: uda-person
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
      