apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-api
  name: person-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: person-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-api
  name: person-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-api
  template:
    metadata:
      labels:
        service: person-api
    spec:
      containers:
      - image: kydq2022/nd064-c2-person-api:latest
        name: person-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        # Kafka
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC_PERSON
      restartPolicy: Always
