apiVersion: v1
kind: Service
metadata:
  labels:
    service: connection-api
  name: connection-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: connection-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connection-api
  name: connection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connection-api
  template:
    metadata:
      labels:
        service: connection-api
    spec:
      containers:
      - image: kydq2022/nd064-c2-connection-api:latest
        name: connection-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        # gRPC
        - name: GRPC_SERVER_ADDRESS
          value: "person-rpc:50051"
      restartPolicy: Always
