apiVersion: v1
kind: Service
metadata:
  labels:
    service: uda-location-consumer
  name: uda-location-consumer
spec:
  ports:
  - name: "5004"
    port: 5004
    targetPort: 5004
    nodePort: 30004
  selector:
    service: uda-location-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: uda-location-consumer
  name: uda-location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: uda-location-consumer
  template:
    metadata:
      labels:
        service: uda-location-consumer
    spec:
      containers:
      - image: samerzmd/uda-location-consumer:latest
        name: uda-location-consumer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always