@startuml
!define RECTANGLE class
!define INTERFACE interface
!define DOWN -[hidden]->

package "Client Apps" {
  RECTANGLE ClientApplications
}

cloud APIGateway {
  RECTANGLE ApiGateway
}

package "Microservices" {
  [Location]
  [Person]
  [Connection]
}

database "Kafka Cluster" {
  [Kafka Topics]
}

package "RPC Servers" {
  [RPC Server - Person]
  [RPC Server - Connection]
}

ClientApplications --down-> ApiGateway
ApiGateway --down-> Location : RESTful API
ApiGateway --down-> Person : RESTful API
ApiGateway --down-> Connection : RESTful API
Location --down-> "Kafka Topics" : Event
Person --down-> "Kafka Topics" : Event
Connection --down-> "Kafka Topics" : Event
"Kafka Topics" --down-> "RPC Server - Person" : Notification
"Kafka Topics" --down-> "RPC Server - Connection" : Notification

@enduml
