# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import persons_pb2 as persons__pb2


class PersonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrieveAllPersons = channel.unary_unary(
                '/udaconnect.PersonService/RetrieveAllPersons',
                request_serializer=persons__pb2.RetrieveAllPersonsRequest.SerializeToString,
                response_deserializer=persons__pb2.ListPerson.FromString,
                )


class PersonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RetrieveAllPersons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrieveAllPersons': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveAllPersons,
                    request_deserializer=persons__pb2.RetrieveAllPersonsRequest.FromString,
                    response_serializer=persons__pb2.ListPerson.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'udaconnect.PersonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PersonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RetrieveAllPersons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/udaconnect.PersonService/RetrieveAllPersons',
            persons__pb2.RetrieveAllPersonsRequest.SerializeToString,
            persons__pb2.ListPerson.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
