# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persons.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpersons.proto\x12\nudaconnect\"Q\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"1\n\nListPerson\x12#\n\x07persons\x18\x01 \x03(\x0b\x32\x12.udaconnect.Person\"\x1b\n\x19RetrieveAllPersonsRequest2d\n\rPersonService\x12S\n\x12RetrieveAllPersons\x12%.udaconnect.RetrieveAllPersonsRequest\x1a\x16.udaconnect.ListPersonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'persons_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PERSON']._serialized_start=29
  _globals['_PERSON']._serialized_end=110
  _globals['_LISTPERSON']._serialized_start=112
  _globals['_LISTPERSON']._serialized_end=161
  _globals['_RETRIEVEALLPERSONSREQUEST']._serialized_start=163
  _globals['_RETRIEVEALLPERSONSREQUEST']._serialized_end=190
  _globals['_PERSONSERVICE']._serialized_start=192
  _globals['_PERSONSERVICE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
